=== dgoncalv/FantasySquare/FantasySquare/SquareFantasy/src/Data/World.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT Worlds (World)+>

<!ELEMENT World (Foreground, Background)+>
    <!ATTLIST World name CDATA #REQUIRED>
    <!ATTLIST World size CDATA #REQUIRED>

<!ELEMENT Foreground (Node*, GateNode*, VillagerNode*, ShopkeeperNode*)>
    <!ELEMENT Node (#PCDATA)>
        <!ATTLIST Node x CDATA #REQUIRED>
        <!ATTLIST Node y CDATA #REQUIRED>

    <!ELEMENT GateNode (#PCDATA)>
        <!ATTLIST GateNode x CDATA #REQUIRED>
        <!ATTLIST GateNode y CDATA #REQUIRED>
        <!ATTLIST GateNode xSpawn CDATA #REQUIRED>
        <!ATTLIST GateNode ySpawn CDATA #REQUIRED>
        <!ATTLIST GateNode lead CDATA #REQUIRED>

    <!ELEMENT VillagerNode (LocationQuest*)>
        <!ATTLIST VillagerNode sprite CDATA #REQUIRED>
        <!ATTLIST VillagerNode x CDATA #REQUIRED>
        <!ATTLIST VillagerNode y CDATA #REQUIRED>
        <!ELEMENT LocationQuest (#PCDATA)>
            <!ATTLIST LocationQuest description CDATA #REQUIRED>
            <!ATTLIST LocationQuest map CDATA #REQUIRED>
            <!ATTLIST LocationQuest x CDATA #REQUIRED>
            <!ATTLIST LocationQuest y CDATA #REQUIRED>

        <!ELEMENT ShopkeeperNode (Item*)>
            <!ATTLIST ShopkeeperNode type CDATA #REQUIRED>
            <!ATTLIST ShopkeeperNode x CDATA #REQUIRED>
            <!ATTLIST ShopkeeperNode y CDATA #REQUIRED>
            <!ELEMENT Item (#PCDATA)>

<!ELEMENT Background (Set)*>
    <!ATTLIST Background biome CDATA #REQUIRED>

<!ELEMENT Set (#PCDATA)>
    <!ATTLIST Set x CDATA #REQUIRED>
    <!ATTLIST Set y CDATA #REQUIRED>

=== dgoncalv/FantasySquare/FantasySquare/SquareFantasy/build/classes/Data/World.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE Worlds SYSTEM "World.dtd">

<Worlds>
    <World name="Plain1" size="10">
        <Foreground>
            <GateNode x="9" y="0" xSpawn="1" ySpawn="0" lead="Plain2">M</GateNode>
            <GateNode x="9" y="1" xSpawn="1" ySpawn="1" lead="Plain2">M</GateNode>
            <GateNode x="9" y="2" xSpawn="1" ySpawn="2" lead="Plain2">M</GateNode>
            <GateNode x="9" y="3" xSpawn="1" ySpawn="3" lead="Plain2">M</GateNode>
            <GateNode x="9" y="4" xSpawn="1" ySpawn="4" lead="Plain2">M</GateNode>
            <GateNode x="9" y="5" xSpawn="1" ySpawn="5" lead="Plain2">M</GateNode>
            <GateNode x="9" y="6" xSpawn="1" ySpawn="6" lead="Plain2">M</GateNode>
            <GateNode x="9" y="7" xSpawn="1" ySpawn="7" lead="Plain2">M</GateNode>
            <GateNode x="9" y="8" xSpawn="1" ySpawn="8" lead="Plain2">M</GateNode>
            <GateNode x="9" y="9" xSpawn="1" ySpawn="9" lead="Plain2">M</GateNode>

            <GateNode x="0" y="9" xSpawn="0" ySpawn="1" lead="Plain4">M</GateNode>
            <GateNode x="1" y="9" xSpawn="1" ySpawn="1" lead="Plain4">M</GateNode>
            <GateNode x="2" y="9" xSpawn="2" ySpawn="1" lead="Plain4">M</GateNode>
            <GateNode x="3" y="9" xSpawn="3" ySpawn="1" lead="Plain4">M</GateNode>
            <GateNode x="4" y="9" xSpawn="4" ySpawn="1" lead="Plain4">M</GateNode>
            <GateNode x="5" y="9" xSpawn="5" ySpawn="1" lead="Plain4">M</GateNode>
            <GateNode x="6" y="9" xSpawn="6" ySpawn="1" lead="Plain4">M</GateNode>
            <GateNode x="7" y="9" xSpawn="7" ySpawn="1" lead="Plain4">M</GateNode>
            <GateNode x="8" y="9" xSpawn="8" ySpawn="1" lead="Plain4">M</GateNode>
            <GateNode x="9" y="9" xSpawn="9" ySpawn="1" lead="Plain4">M</GateNode>
        </Foreground>
        <Background biome="GRASS"></Background>
    </World>
    <World name="Plain4" size="10">
        <Foreground>
            <GateNode x="0" y="0" xSpawn="0" ySpawn="8" lead="Plain1">M</GateNode>
            <GateNode x="1" y="0" xSpawn="1" ySpawn="8" lead="Plain1">M</GateNode>
            <GateNode x="2" y="0" xSpawn="2" ySpawn="8" lead="Plain1">M</GateNode>
            <GateNode x="3" y="0" xSpawn="3" ySpawn="8" lead="Plain1">M</GateNode>
            <GateNode x="4" y="0" xSpawn="4" ySpawn="8" lead="Plain1">M</GateNode>
            <GateNode x="5" y="0" xSpawn="5" ySpawn="8" lead="Plain1">M</GateNode>
            <GateNode x="6" y="0" xSpawn="6" ySpawn="8" lead="Plain1">M</GateNode>
            <GateNode x="7" y="0" xSpawn="7" ySpawn="8" lead="Plain1">M</GateNode>
            <GateNode x="8" y="0" xSpawn="8" ySpawn="8" lead="Plain1">M</GateNode>
            <GateNode x="9" y="0" xSpawn="9" ySpawn="8" lead="Plain1">M</GateNode>

            <GateNode x="9" y="0" xSpawn="1" ySpawn="0" lead="Plain5">M</GateNode>
            <GateNode x="9" y="1" xSpawn="1" ySpawn="1" lead="Plain5">M</GateNode>
            <GateNode x="9" y="2" xSpawn="1" ySpawn="2" lead="Plain5">M</GateNode>
            <GateNode x="9" y="3" xSpawn="1" ySpawn="3" lead="Plain5">M</GateNode>
            <GateNode x="9" y="4" xSpawn="1" ySpawn="4" lead="Plain5">M</GateNode>
            <GateNode x="9" y="5" xSpawn="1" ySpawn="5" lead="Plain5">M</GateNode>
            <GateNode x="9" y="6" xSpawn="1" ySpawn="6" lead="Plain5">M</GateNode>
            <GateNode x="9" y="7" xSpawn="1" ySpawn="7" lead="Plain5">M</GateNode>
            <GateNode x="9" y="8" xSpawn="1" ySpawn="8" lead="Plain5">M</GateNode>
            <GateNode x="9" y="9" xSpawn="1" ySpawn="9" lead="Plain5">M</GateNode>

            <GateNode x="0" y="9" xSpawn="0" ySpawn="1" lead="Plain6">M</GateNode>
            <GateNode x="1" y="9" xSpawn="1" ySpawn="1" lead="Plain6">M</GateNode>
            <GateNode x="2" y="9" xSpawn="2" ySpawn="1" lead="Plain6">M</GateNode>
            <GateNode x="3" y="9" xSpawn="3" ySpawn="1" lead="Plain6">M</GateNode>
            <GateNode x="4" y="9" xSpawn="4" ySpawn="1" lead="Plain6">M</GateNode>
            <GateNode x="5" y="9" xSpawn="5" ySpawn="1" lead="Plain6">M</GateNode>
            <GateNode x="6" y="9" xSpawn="6" ySpawn="1" lead="Plain6">M</GateNode>
            <GateNode x="7" y="9" xSpawn="7" ySpawn="1" lead="Plain6">M</GateNode>
            <GateNode x="8" y="9" xSpawn="8" ySpawn="1" lead="Plain6">M</GateNode>
            <GateNode x="9" y="9" xSpawn="9" ySpawn="1" lead="Plain6">M</GateNode>
        </Foreground>
        <Background biome="GRASS"></Background>
    </World>
    <World name="Plain2" size="10">
        <Foreground>
            <GateNode x="0" y="0" xSpawn="8" ySpawn="0" lead="Plain1">M</GateNode>
            <GateNode x="0" y="1" xSpawn="8" ySpawn="1" lead="Plain1">M</GateNode>
            <GateNode x="0" y="2" xSpawn="8" ySpawn="2" lead="Plain1">M</GateNode>
            <GateNode x="0" y="3" xSpawn="8" ySpawn="3" lead="Plain1">M</GateNode>
            <GateNode x="0" y="4" xSpawn="8" ySpawn="4" lead="Plain1">M</GateNode>
            <GateNode x="0" y="5" xSpawn="8" ySpawn="5" lead="Plain1">M</GateNode>
            <GateNode x="0" y="6" xSpawn="8" ySpawn="6" lead="Plain1">M</GateNode>
            <GateNode x="0" y="7" xSpawn="8" ySpawn="7" lead="Plain1">M</GateNode>
            <GateNode x="0" y="8" xSpawn="8" ySpawn="8" lead="Plain1">M</GateNode>
            <GateNode x="0" y="9" xSpawn="8" ySpawn="9" lead="Plain1">M</GateNode>

            <GateNode x="9" y="0" xSpawn="1" ySpawn="0" lead="Plain3">M</GateNode>
            <GateNode x="9" y="1" xSpawn="1" ySpawn="1" lead="Plain3">M</GateNode>
            <GateNode x="9" y="2" xSpawn="1" ySpawn="2" lead="Plain3">M</GateNode>
            <GateNode x="9" y="3" xSpawn="1" ySpawn="3" lead="Plain3">M</GateNode>
            <GateNode x="9" y="4" xSpawn="1" ySpawn="4" lead="Plain3">M</GateNode>
            <GateNode x="9" y="5" xSpawn="1" ySpawn="5" lead="Plain3">M</GateNode>
            <GateNode x="9" y="6" xSpawn="1" ySpawn="6" lead="Plain3">M</GateNode>
            <GateNode x="9" y="7" xSpawn="1" ySpawn="7" lead="Plain3">M</GateNode>
            <GateNode x="9" y="8" xSpawn="1" ySpawn="8" lead="Plain3">M</GateNode>
            <GateNode x="9" y="9" xSpawn="1" ySpawn="9" lead="Plain3">M</GateNode>

            <GateNode x="0" y="9" xSpawn="0" ySpawn="1" lead="Plain5">M</GateNode>
            <GateNode x="1" y="9" xSpawn="1" ySpawn="1" lead="Plain5">M</GateNode>
            <GateNode x="2" y="9" xSpawn="2" ySpawn="1" lead="Plain5">M</GateNode>
            <GateNode x="3" y="9" xSpawn="3" ySpawn="1" lead="Plain5">M</GateNode>
            <GateNode x="4" y="9" xSpawn="4" ySpawn="1" lead="Plain5">M</GateNode>
            <GateNode x="5" y="9" xSpawn="5" ySpawn="1" lead="Plain5">M</GateNode>
            <GateNode x="6" y="9" xSpawn="6" ySpawn="1" lead="Plain5">M</GateNode>
            <GateNode x="7" y="9" xSpawn="7" ySpawn="1" lead="Plain5">M</GateNode>
            <GateNode x="8" y="9" xSpawn="8" ySpawn="1" lead="Plain5">M</GateNode>
            <GateNode x="9" y="9" xSpawn="9" ySpawn="1" lead="Plain5">M</GateNode>
        </Foreground>
        <Background biome="GRASS"></Background>
    </World>
    <World name="Plain3" size="10">
        <Foreground>
            <GateNode x="0" y="0" xSpawn="8" ySpawn="0" lead="Plain2">M</GateNode>
            <GateNode x="0" y="1" xSpawn="8" ySpawn="1" lead="Plain2">M</GateNode>
            <GateNode x="0" y="2" xSpawn="8" ySpawn="2" lead="Plain2">M</GateNode>
            <GateNode x="0" y="3" xSpawn="8" ySpawn="3" lead="Plain2">M</GateNode>
            <GateNode x="0" y="4" xSpawn="8" ySpawn="4" lead="Plain2">M</GateNode>
            <GateNode x="0" y="5" xSpawn="8" ySpawn="5" lead="Plain2">M</GateNode>
            <GateNode x="0" y="6" xSpawn="8" ySpawn="6" lead="Plain2">M</GateNode>
            <GateNode x="0" y="7" xSpawn="8" ySpawn="7" lead="Plain2">M</GateNode>
            <GateNode x="0" y="8" xSpawn="8" ySpawn="8" lead="Plain2">M</GateNode>
            <GateNode x="0" y="9" xSpawn="8" ySpawn="9" lead="Plain2">M</GateNode>

            <GateNode x="9" y="0" xSpawn="1" ySpawn="0" lead="Desert1">M</GateNode>
            <GateNode x="9" y="1" xSpawn="1" ySpawn="1" lead="Desert1">M</GateNode>
            <GateNode x="9" y="2" xSpawn="1" ySpawn="2" lead="Desert1">M</GateNode>
            <GateNode x="9" y="3" xSpawn="1" ySpawn="3" lead="Desert1">M</GateNode>
            <GateNode x="9" y="4" xSpawn="1" ySpawn="4" lead="Desert1">M</GateNode>
            <GateNode x="9" y="5" xSpawn="1" ySpawn="5" lead="Desert1">M</GateNode>
            <GateNode x="9" y="6" xSpawn="1" ySpawn="6" lead="Desert1">M</GateNode>
            <GateNode x="9" y="7" xSpawn="1" ySpawn="7" lead="Desert1">M</GateNode>
            <GateNode x="9" y="8" xSpawn="1" ySpawn="8" lead="Desert1">M</GateNode>
            <GateNode x="9" y="9" xSpawn="1" ySpawn="9" lead="Desert1">M</GateNode>

            <GateNode x="0" y="9" xSpawn="0" ySpawn="1" lead="Desert2">M</GateNode>
            <GateNode x="1" y="9" xSpawn="1" ySpawn="1" lead="Desert2">M</GateNode>
            <GateNode x="2" y="9" xSpawn="2" ySpawn="1" lead="Desert2">M</GateNode>
            <GateNode x="3" y="9" xSpawn="3" ySpawn="1" lead="Desert2">M</GateNode>
            <GateNode x="4" y="9" xSpawn="4" ySpawn="1" lead="Desert2">M</GateNode>
            <GateNode x="5" y="9" xSpawn="5" ySpawn="1" lead="Desert2">M</GateNode>
            <GateNode x="6" y="9" xSpawn="6" ySpawn="1" lead="Desert2">M</GateNode>
            <GateNode x="7" y="9" xSpawn="7" ySpawn="1" lead="Desert2">M</GateNode>
            <GateNode x="8" y="9" xSpawn="8" ySpawn="1" lead="Desert2">M</GateNode>
            <GateNode x="9" y="9" xSpawn="9" ySpawn="1" lead="Desert2">M</GateNode>
        </Foreground>
        <Background biome="GRASS"></Background>
    </World>
    <World name="Plain5" size="10">
        <Foreground>
            <GateNode x="0" y="0" xSpawn="8" ySpawn="0" lead="Plain4">M</GateNode>
